const fs = require('fs');

fs.writeFileSync('notes.txt', 'this is a note generated by Node.js');

const getNotes = function () {
  return 'Your notes...';
};

getNotes();

module.exports = getNotes;
// const add = function (a, b) {
//   return a + b;
// };

// module.exports = add;
